---
image: ocaml/opam:alpine_ocaml-4.06.0

variables:
  OPAMYES: "yes"

cache:
  key: ${COQ_VERSION}
  paths:
    - ${HOME}/.opam

before_script:
  - opam depext -y conf-m4.1
  - eval $(opam config env)
  - ./configure.sh

test:
  script:
    - make
