---
image: ocaml/opam:alpine_ocaml-4.06.0

variables:
  OPAMYES: "yes"
  COQ_VERSION: 8.7.2

cache:
  key: ${COQ_VERSION}
  paths:
    - ${HOME}/.opam

before_script:
  - opam repo add opam https://opam.ocaml.org
  - opam depext -y conf-m4.1
  - opam install coq.$COQ_VERSION
  - eval $(opam config env)
  - ./configure.sh

test:
  script:
    - make
