addons:
  apt:
    packages:
      - aspcud
      - opam
    sources:
      - avsm

before_cache:
  - rm -rf ~/.opam/log/

cache:
  directories:
    - $HOME/.opam
env:
  - OCAML_VERSION=4.05.0 COQ_VERSION=8.7.2 OPAMYES=yes

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install opam; fi

install:
  - opam init -n --comp $OCAML_VERSION
  - opam update
  - opam install coq.$COQ_VERSION
  - eval $(opam config env)
  - ./configure.sh

language: c

script:
  - make

os:
 - linux
 - osx

