language: c

sudo: required

install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
  - bash -ex .travis-opam.sh
  - ./configure.sh

script:
  - make

env:
  - OCAML_VERSION=4.06


