language: c

addons:
  apt:
    packages:
      - ocaml
      - opam

install:
  - opam init --yes --no-setup --compiler=$OCAML_VERSION
  - eval $(opam config env)
  - opam update
  - ./configure.sh

script:
  - make

env:
  - OCAML_VERSION=4.06


